serverAddr = "18.237.153.223"
serverPort = 7000
auth.token = "quant2024secret"

[[proxies]]
name = "quant-web"
type = "http"
localIP = "127.0.0.1"
localPort = 8071
customDomains = ["18.237.153.223"]

[[proxies]]
name = "quant-api"
type = "http"
localIP = "127.0.0.1"
localPort = 8072
customDomains = ["18.237.153.223"]
locations = ["/api"]
