"""add stock_heat table

Revision ID: 49783c9e80de
Revises: e30ac5ed6fa4
Create Date: 2026-03-02 11:37:52.760983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49783c9e80de'
down_revision: Union[str, None] = 'e30ac5ed6fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_heat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('heat_date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('xq_follow_count', sa.BigInteger(), nullable=True, comment='雪球关注数'),
    sa.Column('xq_follow_rank', sa.Integer(), nullable=True, comment='雪球关注排名'),
    sa.Column('xq_tweet_count', sa.BigInteger(), nullable=True, comment='雪球讨论数'),
    sa.Column('xq_tweet_rank', sa.Integer(), nullable=True, comment='雪球讨论排名'),
    sa.Column('baidu_hot', sa.Boolean(), nullable=False, comment='是否在百度热搜'),
    sa.Column('heat_score', sa.Integer(), nullable=False, comment='综合热度得分(0-100)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'heat_date', name='uq_stock_heat_code_date')
    )
    op.create_index('idx_heat_date', 'stock_heat', ['heat_date'], unique=False)
    op.create_index('idx_heat_score', 'stock_heat', ['heat_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_heat_score', table_name='stock_heat')
    op.drop_index('idx_heat_date', table_name='stock_heat')
    op.drop_table('stock_heat')
    # ### end Alembic commands ###
